-- -- Create a sample table
-- CREATE TABLE IF NOT EXISTS users (
--     id SERIAL PRIMARY KEY,
--     username VARCHAR(50) NOT NULL,
--     email VARCHAR(100) NOT NULL UNIQUE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Insert sample data
-- INSERT INTO users (username, email) VALUES
-- ('alice', 'alice@example.com'),
-- ('bob', 'bob@example.com');